apiVersion: v1
kind: Secret
metadata:
    name: secret-registry
    type: kubernetes.io/dockerconfigjson
    data:
        .dockerconfigjson: |
              "<base64 encoded ~/.docker/config.json-file>"
